# Generated by Django 5.0.6 on 2024-12-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'اکانت کاربری', 'verbose_name_plural': 'اکانت های کاربری'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='do_task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='miss_task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='task_created',
        ),
    ]
