# Generated by Django 5.0.6 on 2024-12-22 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان وظیفه')),
                ('info', models.TextField(max_length=300, verbose_name='توضیحات وظیفه')),
                ('last_time', models.DateTimeField(verbose_name='اتمام مهلت')),
                ('is_important', models.BooleanField(default=False, verbose_name='آیا این وظیفه مهم است')),
                ('is_done', models.BooleanField(default=False, verbose_name='آیا وظیفه انجام شده')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد این وظیفه')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.DateTimeField(verbose_name='یادآور')),
                ('title', models.CharField(max_length=50, verbose_name='متن یادآور')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='task.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'یادآور',
                'verbose_name_plural': 'یادآورها',
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='دسته بندی وظایف')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_groups', to=settings.AUTH_USER_MODEL, verbose_name='اکانت کاربری')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.taskgroup', verbose_name='دسته بندی'),
        ),
        migrations.AddIndex(
            model_name='taskgroup',
            index=models.Index(fields=['-date'], name='task_taskgr_date_3795f4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-date'], name='task_task_date_bc5ed5_idx'),
        ),
    ]
