# Generated by Django 5.0.6 on 2024-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_miss',
            field=models.BooleanField(default=False, verbose_name='آیا وظیفه فراموش شده'),
        ),
    ]
